# Site settings
title: CAT_A_TONIC
email: gregorio.setti@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://desmondhume.github.io" # the base hostname & protocol for your site
twitter_username: GregorioSetti
github_username:  desmondhume
link_separator: "-"

# Build settings
markdown: kramdown
